import Container from './components/Container'
import Navbar from './components/navbar/Navbar'
import './globals.css'
import { Quicksand } from 'next/font/google'

const roboto = Quicksand({ weight: '400', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className = 'w-screen transition-colors fixed px-20'>
          <Navbar />
          <Container>
            {children}
          </Container>
          
        </div>
          
      </body>
    </html>
  )
}
